; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27034.0 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\LK\AppData\Local\Temp\.NETFramework,Version=v4.7.AssemblyAttributes.cpp"
